spring:
    application:
        name: es-service
    data:
      mongodb:
        uri:  mongodb://test:123456@120.78.173.4:27017/test
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE
        username: root
        password: 123456
    jpa:
      hibernate:
        ddl-auto: update
        use-new-id-generator-mappings: false
      show-sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL55Dialect