server:
  port: 9000

spring:
    application:
        name: order-service
    cloud:
      consul:
        enabled: true
        discovery:
          instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
          prefer-ip-address: true
        retry:
          initial-interval: 10
          max-attempts: 15
          max-interval: 30000
    data:
      mongodb:
        uri:  mongodb://test:123456@120.78.173.4:27017/test
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE
        username: root
        password: 123456
    jpa:
      hibernate:
        ddl-auto: update
        use-new-id-generator-mappings: false
      show-sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
    rabbitmq:
      host: localhost
      username: creams_user
      password: Souban701
      port: 5672
    jackson:
      time-zone: PRC

axon:
  distributed:
    enabled: true